In [1]:
from datetime import datetime
import json
from tab_dataset import Cdataset
import pandas as pd
import ntv_pandas as npd
import pathlib

In [2]:
sessions = pd.read_csv('export-charges-manquantes-T4-2025-v4.csv', sep=',', low_memory=False) #, dtype='object')

In [22]:
sessions['start']=sessions['start'].astype('datetime64[ns, UTC]').astype(str)
sessions['end']=sessions['end'].astype('datetime64[ns, UTC]').astype(str)

In [23]:
sessions.to_csv('export-charges-manquantes-T4-2025-v4-corrige.csv', index=False)

In [19]:
tst = sessions[0:10].copy()

In [17]:
tst

,start,end,id_pdc_itinerance,energy,numero_de_pdl
0,2025-10-01 00:05:04 UTC,2025-10-01 00:22:36 UTC,FRIZFEFAST50213,16928,50033215316046
1,2025-10-01 00:08:36 UTC,2025-10-01 01:00:28 UTC,FRM06ENICE12121,32997,25443437
2,2025-10-01 00:09:59.654 UTC,2025-10-01 00:20:41.117 UTC,FRSIGESIGE24211,4065,21474095380932
3,2025-10-01 00:36:37 UTC,2025-10-01 01:22:46 UTC,FRIZFEFAST60013,45112,50088928842518
4,2025-10-01 00:48:52 UTC,2025-10-01 01:40:09 UTC,FRIZFEFAST71913,44980,60004750004096
5,2025-10-01 00:49:01 UTC,2025-10-01 01:24:51 UTC,FRIZFEFAST72211,32519,50073300626309
6,2025-10-01 01:35:48 UTC,2025-10-01 02:11:59 UTC,FRIZFEFAST70911,32477,50001954388625
7,2025-10-01 01:40:36.979 UTC,2025-10-01 01:40:40.561 UTC,FRSIGESIGE44411,3,50000659743580
8,2025-10-01 01:40:47 UTC,2025-10-01 01:59:53 UTC,FRIZFEFAST35211,20117,50072146690150
9,2025-10-01 01:40:47 UTC,2025-10-01 01:59:53 UTC,FRIZFEFAST35211,20117,50072146690150

In [10]:
pd.to_datetime(tst['start'], utc=True, format='mixed')

0          2025-10-01 00:05:04+00:00
1          2025-10-01 00:08:36+00:00
2   2025-10-01 00:09:59.654000+00:00
3          2025-10-01 00:36:37+00:00
4          2025-10-01 00:48:52+00:00
5          2025-10-01 00:49:01+00:00
6          2025-10-01 01:35:48+00:00
7   2025-10-01 01:40:36.979000+00:00
8          2025-10-01 01:40:47+00:00
9          2025-10-01 01:40:47+00:00
Name: start, dtype: datetime64[ns, UTC]

In [12]:
tst['start'].astype('datetime64[ns, UTC]').astype(str)

0           2025-10-01 00:05:04+00:00
1           2025-10-01 00:08:36+00:00
2    2025-10-01 00:09:59.654000+00:00
3           2025-10-01 00:36:37+00:00
4           2025-10-01 00:48:52+00:00
5           2025-10-01 00:49:01+00:00
6           2025-10-01 01:35:48+00:00
7    2025-10-01 01:40:36.979000+00:00
8           2025-10-01 01:40:47+00:00
9           2025-10-01 01:40:47+00:00
Name: start, dtype: object

In [20]:
tst['start']=tst['start'].astype('datetime64[ns, UTC]').astype(str)
tst['end']=tst['end'].astype('datetime64[ns, UTC]').astype(str)
tst

,start,end,id_pdc_itinerance,energy,numero_de_pdl
0,2025-10-01 00:05:04+00:00,2025-10-01 00:22:36+00:00,FRIZFEFAST50213,16928,50033215316046
1,2025-10-01 00:08:36+00:00,2025-10-01 01:00:28+00:00,FRM06ENICE12121,32997,25443437
2,2025-10-01 00:09:59.654000+00:00,2025-10-01 00:20:41.117000+00:00,FRSIGESIGE24211,4065,21474095380932
3,2025-10-01 00:36:37+00:00,2025-10-01 01:22:46+00:00,FRIZFEFAST60013,45112,50088928842518
4,2025-10-01 00:48:52+00:00,2025-10-01 01:40:09+00:00,FRIZFEFAST71913,44980,60004750004096
5,2025-10-01 00:49:01+00:00,2025-10-01 01:24:51+00:00,FRIZFEFAST72211,32519,50073300626309
6,2025-10-01 01:35:48+00:00,2025-10-01 02:11:59+00:00,FRIZFEFAST70911,32477,50001954388625
7,2025-10-01 01:40:36.979000+00:00,2025-10-01 01:40:40.561000+00:00,FRSIGESIGE44411,3,50000659743580
8,2025-10-01 01:40:47+00:00,2025-10-01 01:59:53+00:00,FRIZFEFAST35211,20117,50072146690150
9,2025-10-01 01:40:47+00:00,2025-10-01 01:59:53+00:00,FRIZFEFAST35211,20117,50072146690150

In [21]:
tst.to_csv('tst.csv', index=False)